### ISSUE TITLE
Differences between this and original FP

### ISSUE THREAD

**Issue by nitrokevin** [annrie/FoundationPressNG#1]
Hi just wondering how close this is the the original Ole version of FoundationPress, have you customised it for your own needs or kept it as it was but just more up to date?

**Comment by annrie** [comment]
Hi,nitrokevin.
Thank you for your comment.

As you said, it's a fork of Ole's version of FoundationPress.
I originally forked it, but it was a lot of work, so I'm publishing it as a new project.

I'm not up to date with the read-me, but I've adjusted it to work with the latest web environment, including foundation sites and WordPress gutenberg. I haven't explained it so others don't know how to use it.

I also referred to your and jonbrockett's repositories. I would like to take this opportunity to thank you for your help.

I'm sorry for my poor English.

**Comment by dantahoua** [comment]
Hey! I just post a message on nitrokevin Github to thanks him.
Seems you also made a great work to update ul theme.
We have to make it live again!  
Maybe you should update the documentation a little, seems npm start command do not work, thie git clone still refer to OleFrederik repo, etc. :)

**Comment by annrie** [comment]
Hi dantahoua.

I have reviewed the repository and both mpn start and yarn start seem to be working fine. That's strange.

However, the way yarn2 was installed was wrong, so I fixed that.
Thank you very much.

>　Maybe you should update the documentation a little

I'm sure it's a lot of work to explain how to use wordpress. Maybe you should update the documentation a little bit, it would be a lot of work to explain how to use wordpress, but I think I should definitely explain the Gutenberg affinity.

Thanks for the follow-up and encouragement.

**Comment by dantahoua** [comment]
Weird npm do not start, maybe my node version (12.1)...

**Comment by annrie** [comment]
Hmmm. I tried it with v12.1.0 and there seems to be no problem.
Currently, I am using v12.14.0. Is it possible to change the version?
